### PR TITLE
Feat/navigation

### PR DESCRIPTION
**Pull request by maycon-mello**

### CODE REVIEW

**Comment by sk91** [comment]
@maycon-mello please add .DS_store to gitignore

**Comment by sk91** [comment]
maybe add some common gitignore from https://github.com/github/gitignore ?

**Comment by maycon-mello** [comment]
> maybe add some common gitignore from https://github.com/github/gitignore ?

Yes, it sounds good. Let me check

**Comment by maycon-mello** [comment]
> maybe add some common gitignore from https://github.com/github/gitignore ?

I've added a common gitignore

**Pull request merged**
